---

# Deployment

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: brc
  namespace: gemma
  labels:
    k8s-app: brc
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: brc
  template:
    metadata:
      name: brc
      labels:
        k8s-app: brc
    spec:
      containers:
      - name: brc
        image: vngr/gemma-brc:0.1.0
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: brc.conf.docker
          - name: SUBPATH
            value: /brc
          - name: DATABASE_HOST
            value: postgres-brc
          - name: SECRET_KEY
            value: <REDACTED>
          - name: DATABASE_PASSWORD
            value: <REDACTED>
          - name: SENTRY_DSN
            value: <REDACTED>

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: brc
  namespace: gemma
  labels:
    k8s-app: brc
spec:
  selector:
    k8s-app: brc
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
